environment:
  adminEmail: "admin@admin.com"
  adminPassword: "adminadmin"

server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true